apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ae-nginx
  namespace: ae
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
#      nodeSelector:
#        security-zone: back
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: security-zone
                operator: In
                values:
                - back2
                - autoscaler
      containers:
      - name: nginx
        image: nginx:1.15
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 0.2

