---
apiVersion: v1
kind: Service
metadata:
  name: ae-nginx
  namespace: ae
  labels:
    app: nginx
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP

