apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-128-volume 
  namespace: gluster
spec:
  capacity:
    storage: 128Mi 
  accessModes: 
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster 
    path: /k8s
    readOnly: false
  persistentVolumeReclaimPolicy: Retain


