---
kind: Endpoints
apiVersion: v1
metadata:
  name: glusterfs-cluster
subsets:
- addresses:
  - ip: 192.168.1.118
  ports:
  - port: 1
- addresses:
  - ip: 192.168.1.119
  ports:
  - port: 1
- addresses:
  - ip: 192.168.1.120
  ports:
  - port: 1
