apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pruebagluster
  namespace: gluster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pruebagluster
    spec:
      containers:
      - name: pruebagluster
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: glusterfs
          mountPath: /mnt/glusterfs
      volumes:
      - name: glusterfs
        persistentVolumeClaim:
          claimName: gluster-64-pvc
#        glusterfs:
#          endpoints: glusterfs-cluster
#          path: k8s
#          readOnly: false
#        emptyDir: {}
