apiVersion: apps/v1
kind: Deployment
metadata:
  name: pruebagluster
  namespace: gluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pruebagluster
  template:
    metadata:
      labels:
        app: pruebagluster
    spec:
      containers:
      - name: pruebagluster
        image: javisol/jsa-tools:0.1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: glusterfs
          mountPath: /mnt/glusterfs
      volumes:
      - name: glusterfs
        glusterfs:
          endpoints: glusterfs-cluster
          path: /k8s
          readOnly: false
#        emptyDir: {}
