apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2019-09-24T13:27:21Z"
  name: nginx-nlp-access-secrets
  namespace: nginx-ingress
  resourceVersion: "204327"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/nginx-ingress/roles/nginx-nlp-access-secrets
  uid: d3631327-77b7-4fbc-a6d3-79f1e9e76b1e
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - update
  - create
