apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bind
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: bind
                name: bind
        spec:
            containers:
            - name: bind
              image: sameersbn/bind
              env:
                - name: WEBMIN_ENABLED
                  value: "true"
              ports:
                - containerPort: 53
                  protocol: UDP
                - containerPort: 10000
                  protocol: TCP
              volumeMounts:
                - mountPath: /data
                  name: data
            volumes:
            - name: data
              emptyDir: {}

