apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-nlp-v2
  namespace: nlp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-nlp-v2
    spec:
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 2
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 2
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nginx-nlp-v2
              topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx-nlp-v2
        image: javisol/nginx-nlp:1.3
        imagePullPolicy: Always
        #imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 3
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 5 
          successThreshold: 1
      terminationGracePeriodSeconds: 10     
