apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-writer
rules:
- apiGroups: ["","extensions"] # "" indicates the core API group
  resources: ["pods", "deployments", "daemonsets", "statefulsets"]
  verbs: ["get", "watch", "list", "update", "patch", "delete"]
