apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-viewer
rules:
- apiGroups: ["","extensions"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["get", "watch", "list"]
